"""RRemove duration column

Revision ID: a490ed555eb5
Revises: 3cadbd1c2201
Create Date: 2025-05-31 09:05:08.853890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a490ed555eb5'
down_revision: Union[str, None] = '3cadbd1c2201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('currently_borrowed', sa.Boolean(), nullable=True))
    op.drop_column('books', 'is_read')
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.add_column('books', sa.Column('is_read', sa.BOOLEAN(), nullable=True))
    op.drop_column('books', 'currently_borrowed')
    # ### end Alembic commands ###
